-- Seed challenges data into the database
INSERT INTO public.challenges (
  id,
  title,
  trend,
  description,
  example,
  prize_pool,
  participants,
  solo_participants,
  team_count,
  starts_at,
  ends_at,
  difficulty,
  tags,
  status,
  winner_prize,
  why_relevant,
  sources,
  trend_growth,
  audience_size,
  entry_fee
) VALUES 
(
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'Couple Conflict Resolver',
  'Relationship Arguments',
  'Build an app that helps couples settle disputes fairly. Who''s right? Let AI decide!',
  'Build a ''Couple Who Wins'' app where each partner presents their case and AI picks a winner based on logic & fairness.',
  700,
  350,
  245,
  35,
  now() - interval '16 hours',
  now() + interval '8 hours',
  'beginner',
  ARRAY['AI', 'Relationships', 'Fun'],
  'active',
  630,
  'Couples arguing about chores & decisions is trending on TikTok. ''Who''s right'' videos get millions of views. People want a neutral AI judge.',
  '[{"source": "tiktok", "metric": "Views this week", "value": "12.4M"}, {"source": "google_trends", "metric": "Search growth", "value": "+340%"}]'::jsonb,
  '+340%',
  '18-35 couples',
  2
),
(
  'b2c3d4e5-f6a7-8901-bcde-f12345678901',
  'Doom Scroll Detox',
  'Screen Time Anxiety',
  'Create a tool that breaks the infinite scroll addiction with creative interventions.',
  'An app that detects doom scrolling and interrupts with breathing exercises or reality checks.',
  378,
  189,
  132,
  19,
  now() - interval '26 hours',
  now() - interval '2 hours',
  'intermediate',
  ARRAY['Wellness', 'Productivity', 'Mobile'],
  'voting',
  340.20,
  'Screen time guilt is at an all-time high. Gen Z actively seeking dopamine detox solutions. Huge viral potential.',
  '[{"source": "tiktok", "metric": "Hashtag views", "value": "8.2M"}, {"source": "google_trends", "metric": "Search growth", "value": "+180%"}, {"source": "reddit", "metric": "Posts/week", "value": "2.4K"}]'::jsonb,
  '+180%',
  'Gen Z & Millennials',
  2
),
(
  'c3d4e5f6-a7b8-9012-cdef-123456789012',
  'AI Outfit Judge',
  'Fashion Insecurity',
  'Build an AI that honestly rates outfits before leaving the house.',
  'Upload a mirror selfie, get brutal AI fashion advice with suggestions from your own wardrobe.',
  556,
  278,
  195,
  28,
  now() - interval '50 hours',
  now() - interval '26 hours',
  'advanced',
  ARRAY['Fashion', 'AI Vision', 'Social'],
  'completed',
  500.40,
  '''Rate my outfit'' posts dominate social. AI fashion tools are exploding. People want honest feedback without asking friends.',
  '[{"source": "tiktok", "metric": "Creator videos", "value": "45K"}, {"source": "google_trends", "metric": "Search growth", "value": "+420%"}]'::jsonb,
  '+420%',
  'Fashion-conscious 16-28',
  2
),
(
  'd4e5f6a7-b8c9-0123-defa-234567890123',
  'Side Hustle Validator',
  'Passive Income FOMO',
  'Create a reality-check tool for viral ''get rich'' schemes.',
  'Paste a TikTok side hustle idea, get AI analysis of actual ROI, time investment, and success probability.',
  824,
  412,
  288,
  41,
  now() - interval '74 hours',
  now() - interval '50 hours',
  'intermediate',
  ARRAY['Finance', 'AI', 'Viral'],
  'completed',
  741.60,
  'Fake ''get rich'' content floods TikTok. Users are desperate to know what''s real. Scam-busting content goes viral.',
  '[{"source": "tiktok", "metric": "Related hashtags", "value": "28M views"}, {"source": "freelancer", "metric": "Related gigs", "value": "1.2K"}, {"source": "google_trends", "metric": "Search growth", "value": "+210%"}]'::jsonb,
  '+210%',
  'Aspiring entrepreneurs',
  2
)
ON CONFLICT (id) DO NOTHING;